-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Drop existing tables if they exist (to ensure clean slate if re-run)
drop table if exists products cascade;
drop table if exists sub_categories cascade;
drop table if exists categories cascade;

-- 1. Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  "order" int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Sub Categories Table
create table sub_categories (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id) on delete cascade not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(category_id, name)
);

-- 3. Products Table
create table products (
  id uuid default uuid_generate_v4() primary key,
  sub_id bigint references sub_categories(id) on delete cascade not null,
  name text not null,
  img_urls text[] default '{}',
  external_url text,
  description text,
  specs jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table categories enable row level security;
alter table sub_categories enable row level security;
alter table products enable row level security;

-- Create Policies (Public Read Access)
create policy "Allow public read access on categories"
  on categories for select
  using (true);

create policy "Allow public read access on sub_categories"
  on sub_categories for select
  using (true);

create policy "Allow public read access on products"
  on products for select
  using (true);

-- 4. Profiles Table (For Admin Permission)
-- This links to Supabase Auth (auth.users)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone"
  on profiles for select
  using (true);

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Admins can update profiles"
  on profiles for update
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Grant Admin Write Access to Products/Categories
-- (These policies allow Admins to INSERT/UPDATE/DELETE)

create policy "Allow admin full access on categories"
  on categories
  for all
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Allow admin full access on sub_categories"
  on sub_categories
  for all
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Allow admin full access on products"
  on products
  for all
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

